# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NestedSliding' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NestedSliding
  pod 'MJRefresh'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'NestedSlidingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NestedSlidingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
